######################################################################
# Automatically generated by qmake (2.01a) seg nov 23 09:46:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += frmPrincipal.h gaussjordan.h sistema.h
SOURCES += frmPrincipal.cpp gaussjordan.cpp main.cpp sistema.cpp
