######################################################################
# Automatically generated by qmake (2.01a) ter out 27 10:47:30 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += canvas.hpp \
           funcao.hpp \
           janelaP.hpp \
           bissecao.h \
           parentmethod.hpp \
           posicaofalsa.hpp \
           table.hpp
SOURCES += canvas.cpp \
           funcao.cpp \
           janelaP.cpp \
           main.cpp \
           bissecao.cpp \
           parentmethod.cpp \
           posicaofalsa.cpp \
           table.cpp
QT += opengl
